export const CHECKUSER_REQUEST = 'CHECKUSER_REQUEST';
export const CHECKUSER_SUCCESS = 'CHECKUSER_SUCCESS';
export const CHECKUSER_FAILURE = 'CHECKUSER_FAILURE';

export const INSERTUSER_REQUEST = 'INSERTUSER_REQUEST';
export const INSERTUSER_SUCCESS = 'INSERTUSER_SUCCESS';
export const INSERTUSER_FAILURE = 'INSERTUSER_FAILURE';

export const CREATEACC_REQUEST = 'CREATEACC_REQUEST';
export const CREATEACC_SUCCESS = 'CREATEACC_SUCCESS';
export const CREATEACC_FAILURE = 'CREATEACC_FAILURE';

export const GETACC_REQUEST = 'GETACC_REQUEST';
export const GETACC_SUCCESS = 'GETACC_SUCCESS';
export const GETACC_FAILURE = 'GETACC_FAILURE';

export const GET_TRANSFERS_REQUEST = 'GET_TRANSFERS_REQUEST';
export const GET_TRANSFERS_SUCCESS = 'GET_TRANSFERS_SUCCESS';
export const GET_TRANSFERS_FAILURE = 'GET_TRANSFERS_FAILURE';

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';

export const GET_RECEIVER_REQUEST = 'GET_RECEIVER_REQUEST';
export const GET_RECEIVER_SUCCESS = 'GET_RECEIVER_SUCCESS';
export const GET_RECEIVER_FAILURE = 'GET_RECEIVER_FAILURE';

export const DO_TRANSFER_REQUEST = 'DO_TRANSFER_REQUEST';
export const DO_TRANSFER_SUCCESS = 'DO_TRANSFER_SUCCESS';
export const DO_TRANSFER_FAILURE = 'DO_TRANSFER_FAILURE';